track_days: 7

login_list:
  - ichn-hu
  - SunRunAway
  - dyzsr
  - lzmhhh123
  - XuHuaiyu
  - eurekaka
  - time-and-fate
  - wshwsh12
  - winoros
  - qw4990
  - fzhedu
  - rebelice

org_list:
  - pingcap
  - tikv
