report_post_to:
  owner: ichn-hu
  name: review-promoter
  issue: 1

tracked_days: 7

login_list:
  - SunRunAway
  - ichn-hu
  - dyzsr
  - lzmhhh123
  - XuHuaiyu
  - eurekaka
  - time-and-fate
  - wshwsh12
  - winoros
  - qw4990
  - fzhedu
  - rebelice

org_list:
  - pingcap
  - tikv

tracked_repos:
  - owner: pingcap
    name: tidb
  - owner: pingcap
    name: parser
  - owner: tikv
    name: tikv
  - owner: tikv
    name: pd

